CREATE TABLE bd_parque_ecologico.PARQUE_ECOLOGICO (
COD_PARQUE integer PRIMARY KEY,
NOME varchar(50),
LOCALIZACAO varchar(100),
DATA_CRIACAO date,
TAMANHO integer
);

CREATE TABLE bd_parque_ecologico.PROJETO_DE_CONSERVACAO (
COD_PROJETO integer PRIMARY KEY,
OBJETIVO varchar(100),
DATA_FIM date,
DATA_INICIO date,
FINANCIAMENTO integer
);

CREATE TABLE bd_parque_ecologico.PROJETO_PARQUE (
COD_PARQUE integer,
COD_PROJETO integer,
PRIMARY KEY(COD_PARQUE,COD_PROJETO),
FOREIGN KEY(COD_PROJETO) REFERENCES PROJETO_DE_CONSERVACAO (COD_PROJETO),
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE)
);

CREATE TABLE bd_parque_ecologico.TRILHA (
COD_TRILHA integer PRIMARY KEY,
DISTANCIA integer,
NOME varchar(100)
);

CREATE TABLE bd_parque_ecologico.TRILHA_PARQUE (
COD_PARQUE integer,
COD_TRILHA integer,
PRIMARY KEY(COD_PARQUE,COD_TRILHA),
FOREIGN KEY(COD_TRILHA) REFERENCES TRILHA (COD_TRILHA),
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE)
);

CREATE TABLE bd_parque_ecologico.PESQUISADOR (
COD_PESQUISADOR integer PRIMARY KEY,
NOME varchar(50),
AFILIACAO varchar(100)
);

CREATE TABLE bd_parque_ecologico.PESQUISA_CIENTIFICA (
COD_PESQUISA integer PRIMARY KEY,
DESCRICAO varchar(100),
ORCAMENTO integer,
TITULO varchar(100)
);

CREATE TABLE bd_parque_ecologico.PESQUISA_PESQUISADOR (
COD_PESQUISADOR integer,
COD_PESQUISA integer,
PRIMARY KEY(COD_PESQUISADOR,COD_PESQUISA),
FOREIGN KEY(COD_PESQUISADOR) REFERENCES PESQUISADOR (COD_PESQUISADOR),
FOREIGN KEY(COD_PESQUISA) REFERENCES PESQUISA_CIENTIFICA (COD_PESQUISA)
);

CREATE TABLE bd_parque_ecologico.PESQUISA_PARQUE (
COD_PARQUE integer,
COD_PESQUISA integer,
PRIMARY KEY(COD_PARQUE,COD_PESQUISA),
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE),
FOREIGN KEY(COD_PESQUISA) REFERENCES PESQUISA_CIENTIFICA (COD_PESQUISA)
);

CREATE TABLE bd_parque_ecologico.VISITANTE (
COD_VISITANTE integer PRIMARY KEY,
NOME varchar(50),
DATA_NASCIMENTO date,
CPF bigint UNIQUE NOT NULL
);

CREATE TABLE bd_parque_ecologico.VISITA (
COD_VISITA integer PRIMARY KEY ,
DATA_VISITA datetime,
COD_VISITANTE integer,
COD_PARQUE integer,
FOREIGN KEY(COD_VISITANTE) REFERENCES VISITANTE (COD_VISITANTE),
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE)
);

CREATE TABLE bd_parque_ecologico.EVENTO (
COD_EVENTO integer PRIMARY KEY,
NOME varchar(100),
LOCALIZACAO varchar(100)
);

CREATE TABLE bd_parque_ecologico.EVENTO_PARQUE (
COD_EVENTO_PARQUE integer PRIMARY KEY,
DATA_INICIO date,
DATA_FIM date,
COD_EVENTO integer,
COD_PARQUE integer,
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE),
FOREIGN KEY(COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)
);

CREATE TABLE bd_parque_ecologico.PARTICIPACAO (
COD_PARTICIPACAO integer PRIMARY KEY,
DATA_VISITA date,
COD_EVENTO_PARQUE integer,
COD_VISITANTE integer,
FOREIGN KEY(COD_VISITANTE) REFERENCES VISITANTE (COD_VISITANTE),
FOREIGN KEY(COD_EVENTO_PARQUE) REFERENCES EVENTO_PARQUE (COD_EVENTO_PARQUE)
);

CREATE TABLE bd_parque_ecologico.ESPECIE (
COD_ESPECIE integer PRIMARY KEY,
NOME_CIENTIFICO varchar(50) UNIQUE,
NOME_COMUM varchar(50)
);

CREATE TABLE bd_parque_ecologico.ESPECIE_FAUNA (
TAMANHO integer,
DIETA varchar(100),
COD_ESPECIE integer,
FOREIGN KEY(COD_ESPECIE) REFERENCES ESPECIE (COD_ESPECIE)
);

CREATE TABLE bd_parque_ecologico.ESPECIE_FLORA (
ALTURA integer,
SOLO varchar(100),
COD_ESPECIE integer,
FOREIGN KEY(COD_ESPECIE) REFERENCES ESPECIE (COD_ESPECIE)
);

CREATE TABLE bd_parque_ecologico.ESPECIE_PARQUE (
COD_CONTAGEM integer PRIMARY KEY,
QUANTIDADE integer,
DATA_CONTAGEM date,
COD_PARQUE integer,
COD_ESPECIE integer,
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE),
FOREIGN KEY(COD_ESPECIE) REFERENCES ESPECIE (COD_ESPECIE)
);

CREATE TABLE bd_parque_ecologico.REGISTRO_CLIMATICO (
COD_REGISTRO integer PRIMARY KEY,
DATA_REGISTRO datetime,
UMIDADE integer,
TEMPERATURA integer,
PRECIPITACAO integer,
COD_PARQUE integer,
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE)
);

CREATE TABLE bd_parque_ecologico.MANUTENCAO (
COD_MANUTENCAO integer PRIMARY KEY,
DESCRICAO varchar(100)
);

CREATE TABLE bd_parque_ecologico.MANUTENCAO_PARQUE (
COD_MANUTENCAO_PARQUE integer PRIMARY KEY,
DATA_INICIO date,
DATA_FIM date,
CUSTO integer,
COD_PARQUE integer,
COD_MANUTENCAO integer,
FOREIGN KEY(COD_MANUTENCAO) REFERENCES MANUTENCAO (COD_MANUTENCAO),
FOREIGN KEY(COD_PARQUE) REFERENCES PARQUE_ECOLOGICO (COD_PARQUE)
);